apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmaster
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: anand1590/taskapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: taskmaster-ssvc
spec:
  selector:
    app: taskmaster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
